name: PHP Conformance CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php-version: [ '8.2','8.3', '8.4' ]
        include:
          - os: 'ubuntu-22.04'
            php-version: '8.1'
    name: PHP ${{ matrix.php-version }} Conformance Test
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          packagist.org:443
          proxy.golang.org:443
          repo.packagist.org:443
          storage.googleapis.com:443

    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Install Dependencies
      uses: nick-invision/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer install

    - name: Setup Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: '1.27'

    - name: Run HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@403fda9e6e176aae87646aace9bed075cee8e7fd # v1.8.8
      env:
        FUNCTION_TARGET: 'httpFunc'
        FUNCTION_SIGNATURE_TYPE: 'http'
        FUNCTION_SOURCE: ${{ github.workspace }}/tests/conformance/index.php
      with:
        functionType: 'http'
        useBuildpacks: false
        cmd: "'php -S localhost:8080 router.php'"

    - name: Run Declarative HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@403fda9e6e176aae87646aace9bed075cee8e7fd # v1.8.8
      env:
        FUNCTION_TARGET: 'declarativeHttpFunc'
        FUNCTION_SOURCE: ${{ github.workspace }}/tests/conformance/index.php
      with:
        functionType: 'http'
        useBuildpacks: false
        cmd: "'php -S localhost:8080 router.php'"

    - name: Run Declarative Typed conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@403fda9e6e176aae87646aace9bed075cee8e7fd # v1.8.8
      env:
        FUNCTION_TARGET: 'declarativeTypedFunc'
        FUNCTION_SOURCE: ${{ github.workspace }}/tests/conformance/index.php
      with:
        functionType: 'http'
        declarativeType: 'typed'
        useBuildpacks: false
        cmd: "'php -S localhost:8080 router.php'"

    - name: Run CloudEvent conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@403fda9e6e176aae87646aace9bed075cee8e7fd # v1.8.8
      env:
        FUNCTION_TARGET: 'cloudEventFunc'
        FUNCTION_SIGNATURE_TYPE: 'cloudevent'
        FUNCTION_SOURCE: ${{ github.workspace }}/tests/conformance/index.php
      with:
        functionType: 'cloudevent'
        useBuildpacks: false
        validateMapping: true
        cmd: "'php -S localhost:8080 router.php'"

    - name: Run Declarative CloudEvent conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@403fda9e6e176aae87646aace9bed075cee8e7fd # v1.8.8
      env:
        FUNCTION_TARGET: 'declarativeCloudEventFunc'
        FUNCTION_SOURCE: ${{ github.workspace }}/tests/conformance/index.php
      with:
        functionType: 'cloudevent'
        useBuildpacks: false
        validateMapping: true
        cmd: "'php -S localhost:8080 router.php'"
