name: PHP Lint CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga:latest@sha256:febc59eb26c0b14a2262a3babeb5d98a2cb2c22aa3a6609b50a8422c7ffecdbb
      with:
        args: . --diff --dry-run
