name: PHP Lint CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga:latest@sha256:ed1747b161640445dbbb41744a0c51b6e4e61af4e4bdc285242a6ad60e730dd7
      with:
        args: . --diff --dry-run
