name: PHP Lint CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga:latest@sha256:8015b4986c453a43a77bf7ee11d45c0ccda2b7977b58d1fc8caf26ccdb203662
      with:
        args: . --diff --dry-run
